export const ROUTE_PATHS = {
    HOME: '/',
    LOGIN: '/login',
    ACTION_CENTER: '/action-center',
    CUSTOMERS: '/customers',
    PRODUCTS: '/products',
    TRANSACTIONS: '/transactions',
    PAYMENTS: '/payments',
    WALLETS: '/wallets',
    WALLET_DEPOSITS: '/wallet-deposits',
    PAYOUTS: '/payouts',
    PAYMENT_SETTINGS: '/payment-settings',
    DISPUTES: '/disputes',
    MARKETPLACE_OPERATIONS: '/marketplace-operations',
    OPERATIONS_CONTROL: '/operations-control',
    MARKETPLACE_TRUST: '/marketplace-trust',
    AUDIT_LOGS: '/audit-logs',
    DOCUMENT_TEMPLATES: '/document-templates',
    GENERATED_DOCUMENTS: '/generated-documents',
}
