const STATUS_LABELS = {
    draft: 'Bản nháp',
    pending: 'Đang chờ',
    pending_review: 'Chờ duyệt',
    published: 'Đang hiển thị',
    reserved: 'Đã giữ chỗ',
    completed: 'Hoàn tất',
    rejected: 'Bị từ chối',
    cancelled: 'Đã hủy',
    pending_payment: 'Chờ thanh toán',
    partially_paid: 'Đã thanh toán một phần',
    paid: 'Đã thanh toán',
    handover_pending: 'Chờ xác nhận bàn giao',
    handed_over: 'Đã bàn giao',
    active: 'Đang hoạt động',
    return_pending: 'Chờ xác nhận hoàn trả',
    returned: 'Đã hoàn trả',
    disputed: 'Đang tranh chấp',
    submitted: 'Chờ đối soát',
    confirmed: 'Đã xác nhận',
    overdue: 'Quá hạn',
    unsettled: 'Chưa đối soát',
    held: 'Đang tạm giữ',
    released: 'Đã giải ngân',
    refunded: 'Đã hoàn tiền',
    open: 'Đang mở',
    reviewing: 'Đang xem xét',
    resolved: 'Đã xử lý',
    blocked: 'Đã khóa',
    inactive: 'Ngừng hoạt động',
    approved: 'Đã duyệt',
    critical: 'Nghiêm trọng',
    dismissed: 'Đã đóng',
    failed: 'Thất bại',
    hidden: 'Đã ẩn',
    high: 'Cao',
    low: 'Thấp',
    medium: 'Trung bình',
    new: 'Mới',
    normal: 'Bình thường',
    triaged: 'Đã phân loại',
    urgent: 'Khẩn cấp',
    verified: 'Đã xác minh',
    unverified: 'Chưa xác minh',
    waiting_counterparty: 'Chờ bên còn lại',
    waiting_customer: 'Chờ khách hàng',
    warning: 'Cảnh báo',
    suspended: 'Tạm khóa',
    archived: 'Lưu trữ',
    generated: 'Đã phát hành',
    accepted: 'Đã xác nhận',
    available: 'Sẵn sàng',
    transacting: 'Đang giao dịch',
    rented: 'Đang cho thuê',
    sold: 'Đã bán',
    deprecated: 'Ngừng sử dụng',
    cancelled_by_customer: 'Khách hàng đã hủy',
    superseded: 'Đã thay thế',
}

const VALUE_LABELS = {
    sell: 'Bán',
    rent: 'Cho thuê',
    ninja_school: 'Ninja School',
    dragon_ball: 'Ngọc Rồng',
    avatar: 'Avatar',
    game_account: 'Tài khoản trò chơi',
    item: 'Vật phẩm',
    currency: 'Tiền tệ trong game',
    service: 'Dịch vụ',
    dispute_opened: 'Mở tranh chấp',
    rental_returned: 'Tài sản đã hoàn trả',
    rental_active: 'Giao dịch thuê đang hoạt động',
    transaction_completed: 'Giao dịch đã hoàn tất',
    payment_due: 'Sắp đến hạn thanh toán',
    withdrawal_approved: 'Yêu cầu rút tiền đã duyệt',
    wallet_transaction: 'Giao dịch ví',
    withdrawal_request: 'Yêu cầu rút tiền',
    product: 'Sản phẩm',
    open_dispute_high_value: 'Tranh chấp giá trị cao',
    payout_account_review: 'Đối chiếu tài khoản nhận tiền',
    not_as_described: 'Sản phẩm không đúng mô tả',
    other: 'Lý do khác',
    cancel_refund: 'Hủy giao dịch và hoàn tiền',
    release_seller: 'Giải ngân cho người bán',
    partial_refund: 'Hoàn tiền một phần',
    reopen: 'Mở lại xử lý',
    purchase: 'Mua tài khoản',
    rental: 'Thuê tài khoản',
    sale: 'Bán tài khoản',
    buyer: 'Người mua',
    seller: 'Người bán',
    renter: 'Người thuê',
    lessor: 'Người cho thuê',
    installment: 'Trả góp',
    deposit: 'Đặt cọc',
    full: 'Thanh toán đủ',
    periodic: 'Theo từng chu kỳ',
    upfront: 'Thu trước toàn kỳ',
    security_deposit: 'Tiền cọc thuê',
    rental_fee: 'Tiền thuê',
    principal: 'Tiền mua tài khoản',
    bank: 'Chuyển khoản ngân hàng',
    wallet: 'Số dư ví',
    admin: 'Quản trị viên',
    after_handover: 'Sau bàn giao',
    announcement: 'Thông báo',
    appeal: 'Khiếu nại lại',
    before_handover: 'Trước bàn giao',
    business_license: 'Giấy phép kinh doanh',
    buyer_guide: 'Hướng dẫn người mua',
    cancellation: 'Yêu cầu hủy',
    citizen_id: 'Căn cước công dân',
    completion_minutes: 'Biên bản hoàn tất',
    customer: 'Khách hàng',
    deposit_confirmation: 'Xác nhận đặt cọc',
    dispute: 'Tranh chấp',
    dispute_minutes: 'Biên bản tranh chấp',
    dispute_resolution: 'Xử lý tranh chấp',
    faq: 'Câu hỏi thường gặp',
    guide: 'Hướng dẫn',
    handover: 'Bàn giao',
    handover_issue: 'Sự cố bàn giao',
    handover_minutes: 'Biên bản bàn giao',
    installment_appendix: 'Phụ lục trả góp',
    passport: 'Hộ chiếu',
    payment_confirmation: 'Xác nhận thanh toán',
    payment_issue: 'Sự cố thanh toán',
    platform_transaction_record: 'Phiếu ghi nhận giao dịch',
    policy: 'Chính sách',
    privacy: 'Chính sách bảo mật',
    refund: 'Yêu cầu hoàn tiền',
    refund_settlement: 'Hoàn tiền và đối soát',
    rental_record: 'Hồ sơ thuê',
    return_issue: 'Sự cố hoàn trả',
    return_minutes: 'Biên bản hoàn trả',
    risk_notice: 'Cảnh báo rủi ro',
    sale_record: 'Hồ sơ mua bán',
    security_checklist: 'Kiểm tra bảo mật',
    seller_guide: 'Hướng dẫn người bán',
    snapshot: 'Biên bản hiện trạng',
    support: 'Hỗ trợ',
    system: 'Hệ thống',
    terms: 'Điều khoản sử dụng',
    topic: 'Chủ đề',
    transaction: 'Giao dịch',
    hour: 'Giờ',
    day: 'Ngày',
    week: 'Tuần',
    month: 'Tháng',
    business_trail: 'Lịch sử nghiệp vụ',
    system_operation: 'Thao tác hệ thống',
    validation: 'Lỗi xác thực dữ liệu',
    security: 'Sự kiện bảo mật',
    created: 'Tạo mới',
    updated: 'Cập nhật',
    deleted: 'Xóa',
    restored: 'Khôi phục',
    http_mutation: 'Yêu cầu thay đổi',
    validation_failed: 'Dữ liệu không hợp lệ',
    generated_document: 'Tài liệu phát hành',
    payment: 'Thanh toán',
    notification: 'Thông báo',
    risk_flag: 'Cảnh báo rủi ro',
    marketplace_review: 'Đánh giá Marketplace',
}

export const statusLabel = (value, fallback = 'Đang xử lý') =>
    STATUS_LABELS[value] || VALUE_LABELS[value] || fallback
export const valueLabel = (value, fallback = '—') =>
    VALUE_LABELS[value] ||
    STATUS_LABELS[value] ||
    (value ? String(value).replaceAll('_', ' ') : fallback)
export const statusColor = (value) => {
    if (
        [
            'completed',
            'confirmed',
            'published',
            'paid',
            'returned',
            'resolved',
            'active',
            'released',
            'refunded',
            'approved',
            'accepted',
            'verified',
            'normal',
        ].includes(value)
    )
        return 'green'
    if (
        ['rejected', 'cancelled', 'blocked', 'disputed', 'failed'].includes(
            value,
        )
    )
        return 'red'
    if (
        [
            'submitted',
            'pending',
            'pending_review',
            'pending_payment',
            'partially_paid',
            'handover_pending',
            'return_pending',
            'reserved',
            'held',
            'unsettled',
            'overdue',
            'reviewing',
            'triaged',
            'waiting_customer',
            'waiting_counterparty',
            'warning',
        ].includes(value)
    )
        return 'gold'
    if (['high', 'critical', 'urgent'].includes(value)) return 'red'
    if (['medium'].includes(value)) return 'orange'
    return 'default'
}
